import test from 'node:test';import assert from 'node:assert/strict';
import {trend,population,days,mean,sample,correlation,plotY,change,assess} from './model.mjs';
test('axis framing changes coordinates but not data or statistics',()=>{const before=[...trend];assert.notEqual(plotY(50,0,60),plotY(50,48,60));assert.deepEqual(trend,before);assert.deepEqual(change(),{absolute:4,percent:8});assert.equal(plotY(48,48,60),160);assert.equal(plotY(60,48,60),0);assert.throws(()=>plotY(50,60,48));});
test('complete population has 20% club membership and mean42',()=>{assert.equal(population.length,100);assert.equal(new Set(population.map(x=>x.id)).size,100);assert.equal(population.filter(x=>x.club).length,20);assert.equal(mean(population.map(x=>x.minutes)),42);});
test('increasing club sample preserves exclusion and biased mean',()=>{for(const size of [5,10,20])for(let seed=1;seed<50;seed++){const x=sample('club',size,seed);assert.equal(x.length,size);assert.equal(new Set(x.map(r=>r.id)).size,size);assert.ok(x.every(r=>r.club));assert.equal(mean(x.map(r=>r.minutes)),90);}});
test('all-resident draws reproduce, vary, include non-members and never mutate population',()=>{const before=JSON.stringify(population);assert.deepEqual(sample('random',20,9),sample('random',20,9));assert.notDeepEqual(sample('random',20,9),sample('random',20,10));const seen=new Set();for(let seed=1;seed<=500;seed++){const x=sample('random',20,seed);assert.equal(new Set(x.map(r=>r.id)).size,20);x.forEach(r=>seen.add(r.id));}assert.equal(seen.size,100);assert.ok(sample('random',20,1).some(x=>!x.club));assert.equal(JSON.stringify(population),before);});
test('invalid sample states are rejected',()=>{assert.throws(()=>sample('unknown',5));assert.throws(()=>sample('random',0));assert.throws(()=>sample('club',30));});
test('factorial weather dataset has18 unique points with pooled but no within-group correlation',()=>{assert.equal(days.length,18);assert.equal(new Set(days.map(x=>JSON.stringify(x))).size,18);assert.ok(correlation(days)>.9);for(const g of ['Cool','Warm'])assert.equal(correlation(days.filter(x=>x.weather===g)),0);});
test('feedback does not reward common misconceptions',()=>{assert.equal(assess('axis','same'),true);assert.equal(assess('axis','false'),false);assert.equal(assess('sample','large'),false);assert.equal(assess('sample','coverage'),true);assert.equal(assess('cause','cause'),false);assert.equal(assess('cause','weather'),true);});
